spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sharenote
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
mybatis-plus:
  mapper-locations: /mapper/*/**
